import { MemberProfile, IconItem } from '@/types/game';

// Master pool of 90 diverse, non-business distractor items (food, sports, animals, space, music, weather, toys)
export const MASTER_DISTRACTOR_ITEMS: IconItem[] = [
  // Foods & Fruits (20)
  { id: 'md1', type: 'emoji', value: '🍎', label: 'Apple' },
  { id: 'md2', type: 'emoji', value: '🍌', label: 'Banana' },
  { id: 'md3', type: 'emoji', value: '🍉', label: 'Watermelon' },
  { id: 'md4', type: 'emoji', value: '🍇', label: 'Grapes' },
  { id: 'md5', type: 'emoji', value: '🍓', label: 'Strawberry' },
  { id: 'md6', type: 'emoji', value: '🍒', label: 'Cherries' },
  { id: 'md7', type: 'emoji', value: '🍍', label: 'Pineapple' },
  { id: 'md8', type: 'emoji', value: '🥑', label: 'Avocado' },
  { id: 'md9', type: 'emoji', value: '🍑', label: 'Peach' },
  { id: 'md10', type: 'emoji', value: '🍋', label: 'Lemon' },
  { id: 'md11', type: 'emoji', value: '🍕', label: 'Pizza' },
  { id: 'md12', type: 'emoji', value: '🍔', label: 'Burger' },
  { id: 'md13', type: 'emoji', value: '🍟', label: 'Fries' },
  { id: 'md14', type: 'emoji', value: '🌭', label: 'Hotdog' },
  { id: 'md15', type: 'emoji', value: '🍿', label: 'Popcorn' },
  { id: 'md16', type: 'emoji', value: '🥨', label: 'Pretzel' },
  { id: 'md17', type: 'emoji', value: '🌮', label: 'Taco' },
  { id: 'md18', type: 'emoji', value: '🍩', label: 'Donut' },
  { id: 'md19', type: 'emoji', value: '🍦', label: 'Ice Cream' },
  { id: 'md20', type: 'emoji', value: '🧁', label: 'Cupcake' },

  // Sports & Games (15)
  { id: 'md21', type: 'emoji', value: '⚽', label: 'Soccer' },
  { id: 'md22', type: 'emoji', value: '🏀', label: 'Basketball' },
  { id: 'md23', type: 'emoji', value: '🏈', label: 'Football' },
  { id: 'md24', type: 'emoji', value: '⚾', label: 'Baseball' },
  { id: 'md25', type: 'emoji', value: '🎾', label: 'Tennis' },
  { id: 'md26', type: 'emoji', value: '🏐', label: 'Volleyball' },
  { id: 'md27', type: 'emoji', value: '🎳', label: 'Bowling' },
  { id: 'md28', type: 'emoji', value: '🏓', label: 'Ping Pong' },
  { id: 'md29', type: 'emoji', value: '🛹', label: 'Skateboard' },
  { id: 'md30', type: 'emoji', value: '🎯', label: 'Darts' },
  { id: 'md31', type: 'emoji', value: '🎲', label: 'Dice' },
  { id: 'md32', type: 'lucide', value: 'Gamepad2', label: 'Gamepad' },
  { id: 'md33', type: 'emoji', value: '🧩', label: 'Puzzle' },
  { id: 'md34', type: 'emoji', value: '🪁', label: 'Kite' },
  { id: 'md35', type: 'emoji', value: '🪀', label: 'Yo-Yo' },

  // Animals & Wildlife (20)
  { id: 'md36', type: 'emoji', value: '🐶', label: 'Dog' },
  { id: 'md37', type: 'emoji', value: '🐱', label: 'Cat' },
  { id: 'md38', type: 'emoji', value: '🦁', label: 'Lion' },
  { id: 'md39', type: 'emoji', value: '🐯', label: 'Tiger' },
  { id: 'md40', type: 'emoji', value: '🐻', label: 'Bear' },
  { id: 'md41', type: 'emoji', value: '🐼', label: 'Panda' },
  { id: 'md42', type: 'emoji', value: '🦊', label: 'Fox' },
  { id: 'md43', type: 'emoji', value: '🐰', label: 'Rabbit' },
  { id: 'md44', type: 'emoji', value: '🐸', label: 'Frog' },
  { id: 'md45', type: 'emoji', value: '🐙', label: 'Octopus' },
  { id: 'md46', type: 'emoji', value: '🐬', label: 'Dolphin' },
  { id: 'md47', type: 'emoji', value: '🐢', label: 'Turtle' },
  { id: 'md48', type: 'emoji', value: '🦉', label: 'Owl' },
  { id: 'md49', type: 'emoji', value: '🦋', label: 'Butterfly' },
  { id: 'md50', type: 'emoji', value: '🐝', label: 'Bee' },
  { id: 'md51', type: 'lucide', value: 'Cat', label: 'Pet Cat' },
  { id: 'md52', type: 'lucide', value: 'Dog', label: 'Pet Dog' },
  { id: 'md53', type: 'lucide', value: 'Fish', label: 'Fish' },
  { id: 'md54', type: 'lucide', value: 'Bug', label: 'Bug' },
  { id: 'md55', type: 'lucide', value: 'Bird', label: 'Bird' },

  // Space & Fantasy (15)
  { id: 'md56', type: 'emoji', value: '🚀', label: 'Rocket' },
  { id: 'md57', type: 'emoji', value: '🛸', label: 'UFO' },
  { id: 'md58', type: 'emoji', value: '👾', label: 'Alien' },
  { id: 'md59', type: 'emoji', value: '🤖', label: 'Robot' },
  { id: 'md60', type: 'emoji', value: '🔮', label: 'Orb' },
  { id: 'md61', type: 'emoji', value: '👻', label: 'Ghost' },
  { id: 'md62', type: 'emoji', value: '🦄', label: 'Unicorn' },
  { id: 'md63', type: 'emoji', value: '🪐', label: 'Planet' },
  { id: 'md64', type: 'emoji', value: '🌕', label: 'Full Moon' },
  { id: 'md65', type: 'emoji', value: '☄️', label: 'Comet' },
  { id: 'md66', type: 'lucide', value: 'Ghost', label: 'Ghost Character' },
  { id: 'md67', type: 'lucide', value: 'Anchor', label: 'Anchor' },
  { id: 'md68', type: 'lucide', value: 'Rocket', label: 'Space Rocket' },
  { id: 'md69', type: 'lucide', value: 'Sparkle', label: 'Sparkle' },
  { id: 'md70', type: 'emoji', value: '🎈', label: 'Balloon' },

  // Music, Nature & Weather (20)
  { id: 'md71', type: 'emoji', value: '🎸', label: 'Guitar' },
  { id: 'md72', type: 'emoji', value: '🥁', label: 'Drums' },
  { id: 'md73', type: 'emoji', value: '🎷', label: 'Saxophone' },
  { id: 'md74', type: 'emoji', value: '🎺', label: 'Trumpet' },
  { id: 'md75', type: 'emoji', value: '🎧', label: 'Headphones' },
  { id: 'md76', type: 'emoji', value: '🎤', label: 'Microphone' },
  { id: 'md77', type: 'lucide', value: 'Headphones', label: 'Audio' },
  { id: 'md78', type: 'emoji', value: '🌵', label: 'Cactus' },
  { id: 'md79', type: 'emoji', value: '🍄', label: 'Mushroom' },
  { id: 'md80', type: 'emoji', value: '🌻', label: 'Sunflower' },
  { id: 'md81', type: 'emoji', value: '🌈', label: 'Rainbow' },
  { id: 'md82', type: 'emoji', value: '⚡', label: 'Lightning' },
  { id: 'md83', type: 'emoji', value: '❄️', label: 'Snowflake' },
  { id: 'md84', type: 'emoji', value: '🏕️', label: 'Camping' },
  { id: 'md85', type: 'emoji', value: '🌲', label: 'Pine Tree' },
  { id: 'md86', type: 'emoji', value: '🏔️', label: 'Mountain' },
  { id: 'md87', type: 'lucide', value: 'Cookie', label: 'Cookie' },
  { id: 'md88', type: 'lucide', value: 'Tent', label: 'Tent' },
  { id: 'md89', type: 'lucide', value: 'Sun', label: 'Sunlight' },
  { id: 'md90', type: 'lucide', value: 'CloudRain', label: 'Rain Cloud' },
];

export const DEFAULT_DISTRACTOR_POOL: IconItem[] = MASTER_DISTRACTOR_ITEMS.slice(0, 30);

// Generates a 100% unique 30-item distractor array for each member based on their index offset
export function getMemberUniqueDistractors(memberIndex: number, targetIcons: IconItem[]): IconItem[] {
  const targetValues = new Set(targetIcons.map((t) => t.value.toLowerCase()));
  const targetLabels = new Set(targetIcons.map((t) => (t.label || '').toLowerCase()));

  const result: IconItem[] = [];
  const total = MASTER_DISTRACTOR_ITEMS.length;

  // Prime step rotation so every member gets a unique selection & order of distractors
  const prime = 13;
  const startOffset = (memberIndex * prime) % total;

  for (let i = 0; i < total * 2 && result.length < 30; i++) {
    const item = MASTER_DISTRACTOR_ITEMS[(startOffset + i) % total];
    const val = item.value.toLowerCase();
    const lbl = (item.label || '').toLowerCase();

    if (
      !targetValues.has(val) &&
      !targetLabels.has(lbl) &&
      !result.some((r) => r.value === item.value)
    ) {
      result.push({
        ...item,
        id: `dist_${memberIndex + 1}_${result.length + 1}`,
      });
    }
  }

  return result;
}

const RAW_INITIAL_MEMBERS: MemberProfile[] = [
  {
    id: 'm1',
    name: 'Amit Chang',
    category: 'UPVC Doors & Windows',
    company: 'Fenestra Solutions',
    targetIcons: [
      { id: 't1_1', type: 'emoji', value: '🚪', label: 'Door' },
      { id: 't1_2', type: 'emoji', value: '🪟', label: 'Window' },
      { id: 't1_3', type: 'emoji', value: '🏠', label: 'House' },
      { id: 't1_4', type: 'emoji', value: '🏗️', label: 'Construction & Fitting' },
      { id: 't1_5', type: 'lucide', value: 'DoorClosed', label: 'UPVC Door' },
      { id: 't1_6', type: 'lucide', value: 'DoorOpen', label: 'Open Door' },
      { id: 't1_7', type: 'lucide', value: 'Home', label: 'Home & Property' },
      { id: 't1_8', type: 'lucide', value: 'LayoutGrid', label: 'Window Glazing & Panes' },
      { id: 't1_9', type: 'lucide', value: 'Wrench', label: 'Professional Installation' },
      { id: 't1_10', type: 'lucide', value: 'Lock', label: 'Multi-Point Locking' },
    ],
    distractorIcons: [
      // Food
      { id: 'ad1', type: 'emoji', value: '🍕', label: 'Pizza' },
      { id: 'ad2', type: 'emoji', value: '🍔', label: 'Burger' },
      { id: 'ad3', type: 'emoji', value: '🍿', label: 'Popcorn' },
      { id: 'ad4', type: 'emoji', value: '🍦', label: 'Ice Cream' },
      { id: 'ad5', type: 'emoji', value: '🍩', label: 'Donut' },
      { id: 'ad6', type: 'emoji', value: '🍎', label: 'Apple' },
      // Finance
      { id: 'ad7', type: 'emoji', value: '💰', label: 'Money Bag' },
      { id: 'ad8', type: 'emoji', value: '💳', label: 'Credit Card' },
      { id: 'ad9', type: 'lucide', value: 'Banknote', label: 'Banknote' },
      { id: 'ad10', type: 'lucide', value: 'TrendingUp', label: 'Stock Chart' },
      { id: 'ad11', type: 'lucide', value: 'Landmark', label: 'Bank Vault' },
      { id: 'ad12', type: 'emoji', value: '🪙', label: 'Gold Coin' },
      // Law
      { id: 'ad13', type: 'emoji', value: '⚖️', label: 'Scales of Justice' },
      { id: 'ad14', type: 'lucide', value: 'Scale', label: 'Justice Scale' },
      { id: 'ad15', type: 'lucide', value: 'Gavel', label: 'Judge Gavel' },
      { id: 'ad16', type: 'lucide', value: 'Briefcase', label: 'Law Briefcase' },
      { id: 'ad17', type: 'emoji', value: '📜', label: 'Legal Scroll' },
      { id: 'ad18', type: 'emoji', value: '🏛️', label: 'Courthouse' },
      // Entertainment
      { id: 'ad19', type: 'emoji', value: '🎬', label: 'Movie Clapper' },
      { id: 'ad20', type: 'lucide', value: 'Clapperboard', label: 'Cinema' },
      { id: 'ad21', type: 'emoji', value: '🎧', label: 'Headphones' },
      { id: 'ad22', type: 'emoji', value: '🎸', label: 'Guitar' },
      { id: 'ad23', type: 'lucide', value: 'Ticket', label: 'Movie Ticket' },
      { id: 'ad24', type: 'emoji', value: '🎮', label: 'Gaming' },
      // Mountains & Outdoor
      { id: 'ad25', type: 'emoji', value: '🏔️', label: 'Snow Mountain' },
      { id: 'ad26', type: 'lucide', value: 'Mountain', label: 'Mountain Peak' },
      { id: 'ad27', type: 'lucide', value: 'MountainSnow', label: 'Alpine Peak' },
      { id: 'ad28', type: 'emoji', value: '🏕️', label: 'Camping Tent' },
      { id: 'ad29', type: 'lucide', value: 'Tent', label: 'Camp Site' },
      { id: 'ad30', type: 'emoji', value: '🌲', label: 'Pine Forest' },
    ],
  },
  {
    id: 'm2',
    name: 'Manthan Pawar',
    category: 'Branding Consultant',
    company: 'Creative Spectrum',
    targetIcons: [
      { id: 't2_1', type: 'emoji', value: '🎨', label: 'Palette' },
      { id: 't2_2', type: 'emoji', value: '🖌️', label: 'Brush' },
      { id: 't2_3', type: 'emoji', value: '✨', label: 'Sparkles' },
      { id: 't2_4', type: 'lucide', value: 'Palette', label: 'Lucide Palette' },
      { id: 't2_5', type: 'lucide', value: 'PenTool', label: 'Pen Tool' },
      { id: 't2_6', type: 'lucide', value: 'Stamp', label: 'Brand Logo & Seal' },
      { id: 't2_7', type: 'emoji', value: '📐', label: 'Ruler' },
      { id: 't2_8', type: 'lucide', value: 'Image', label: 'Image' },
      { id: 't2_9', type: 'emoji', value: '🖼️', label: 'Picture' },
      { id: 't2_10', type: 'lucide', value: 'Layers', label: 'Layers' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm3',
    name: 'Parth Shah',
    category: 'Plywood & Laminates',
    company: 'Shah Plywoods',
    targetIcons: [
      { id: 't3_1', type: 'emoji', value: '🪵', label: 'Wood' },
      { id: 't3_2', type: 'emoji', value: '🪑', label: 'Chair' },
      { id: 't3_3', type: 'emoji', value: '🪓', label: 'Timber & Lumber' },
      { id: 't3_4', type: 'lucide', value: 'Columns', label: 'Plywood & Laminate Strips' },
      { id: 't3_5', type: 'lucide', value: 'Ruler', label: 'Sheet Measurement' },
      { id: 't3_6', type: 'emoji', value: '🔨', label: 'Hammer' },
      { id: 't3_7', type: 'lucide', value: 'ShieldCheck', label: 'Waterproof Marine Grade' },
      { id: 't3_8', type: 'emoji', value: '🛋️', label: 'Couch' },
      { id: 't3_9', type: 'lucide', value: 'Building', label: 'Building' },
      { id: 't3_10', type: 'emoji', value: '🪚', label: 'Saw' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm4',
    name: 'Mohit Kapoor',
    category: 'Mutual Funds',
    company: 'Kapoor Investments',
    targetIcons: [
      { id: 't4_1', type: 'emoji', value: '📈', label: 'Growth' },
      { id: 't4_2', type: 'emoji', value: '💰', label: 'Money' },
      { id: 't4_3', type: 'emoji', value: '💵', label: 'Cash' },
      { id: 't4_4', type: 'lucide', value: 'TrendingUp', label: 'Trend' },
      { id: 't4_5', type: 'lucide', value: 'PiggyBank', label: 'Savings' },
      { id: 't4_6', type: 'lucide', value: 'DollarSign', label: 'Dollar' },
      { id: 't4_7', type: 'emoji', value: '🏦', label: 'Bank' },
      { id: 't4_8', type: 'lucide', value: 'PieChart', label: 'Portfolio' },
      { id: 't4_9', type: 'emoji', value: '💎', label: 'Wealth' },
      { id: 't4_10', type: 'lucide', value: 'Wallet', label: 'Wallet' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm5',
    name: 'Gireesh Vispute',
    category: 'Interior Designer – Residential',
    company: 'Vispute Design Studio',
    targetIcons: [
      { id: 't5_1', type: 'emoji', value: '🛋️', label: 'Sofa' },
      { id: 't5_2', type: 'emoji', value: '🏠', label: 'Home' },
      { id: 't5_3', type: 'emoji', value: '🛏️', label: 'Bed' },
      { id: 't5_4', type: 'lucide', value: 'Home', label: 'Home' },
      { id: 't5_5', type: 'lucide', value: 'Paintbrush', label: 'Paint' },
      { id: 't5_6', type: 'lucide', value: 'Lamp', label: 'Lighting' },
      { id: 't5_7', type: 'emoji', value: '🖼️', label: 'Decor' },
      { id: 't5_8', type: 'lucide', value: 'Sparkles', label: 'Aesthetic' },
      { id: 't5_9', type: 'emoji', value: '🪴', label: 'Plant' },
      { id: 't5_10', type: 'lucide', value: 'Compass', label: 'Plan' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm6',
    name: 'KD Gaikwad',
    category: 'Advocate – Conveyance',
    company: 'Gaikwad Legal',
    targetIcons: [
      { id: 't6_1', type: 'emoji', value: '⚖️', label: 'Scales' },
      { id: 't6_2', type: 'emoji', value: '📜', label: 'Deed' },
      { id: 't6_3', type: 'emoji', value: '🏛️', label: 'Court' },
      { id: 't6_4', type: 'lucide', value: 'Scale', label: 'Law' },
      { id: 't6_5', type: 'lucide', value: 'FileText', label: 'Document' },
      { id: 't6_6', type: 'lucide', value: 'Stamp', label: 'Registration' },
      { id: 't6_7', type: 'emoji', value: '✒️', label: 'Signature' },
      { id: 't6_8', type: 'lucide', value: 'Shield', label: 'Protection' },
      { id: 't6_9', type: 'emoji', value: '🔑', label: 'Property Title' },
      { id: 't6_10', type: 'lucide', value: 'Key', label: 'Key' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm7',
    name: 'Shraddha More',
    category: 'Architect – Residential',
    company: 'More Architects',
    targetIcons: [
      { id: 't7_1', type: 'emoji', value: '📐', label: 'Blueprint' },
      { id: 't7_2', type: 'emoji', value: '🏡', label: 'Bungalow' },
      { id: 't7_3', type: 'emoji', value: '🏢', label: 'Architecture' },
      { id: 't7_4', type: 'lucide', value: 'Ruler', label: 'Ruler' },
      { id: 't7_5', type: 'lucide', value: 'Compass', label: 'Plan' },
      { id: 't7_6', type: 'lucide', value: 'Building', label: 'Structure' },
      { id: 't7_7', type: 'emoji', value: '✏️', label: 'Pencil' },
      { id: 't7_8', type: 'lucide', value: 'PenTool', label: 'Draft' },
      { id: 't7_9', type: 'emoji', value: '🏛️', label: 'Design' },
      { id: 't7_10', type: 'lucide', value: 'Home', label: 'Residence' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm8',
    name: 'Bhushan Suthar',
    category: 'Modular Furniture',
    company: 'Suthar Modulars',
    targetIcons: [
      { id: 't8_1', type: 'emoji', value: '🪑', label: 'Modular Chair' },
      { id: 't8_2', type: 'emoji', value: '🛋️', label: 'Modular Sofa' },
      { id: 't8_3', type: 'emoji', value: '🗄️', label: 'Cabinet' },
      { id: 't8_4', type: 'lucide', value: 'Box', label: 'Modular Unit' },
      { id: 't8_5', type: 'lucide', value: 'Grid', label: 'Grid' },
      { id: 't8_6', type: 'lucide', value: 'Layers', label: 'Assembly' },
      { id: 't8_7', type: 'emoji', value: '🚪', label: 'Wardrobe' },
      { id: 't8_8', type: 'lucide', value: 'Wrench', label: 'Setup' },
      { id: 't8_9', type: 'emoji', value: '🛏️', label: 'Modular Bed' },
      { id: 't8_10', type: 'lucide', value: 'Maximize', label: 'Space Saving' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm9',
    name: 'Sidharth Gokhale',
    category: 'Vintage Furniture',
    company: 'Gokhale Antiques',
    targetIcons: [
      { id: 't9_1', type: 'emoji', value: '🕰️', label: 'Vintage Clock' },
      { id: 't9_2', type: 'emoji', value: '🏺', label: 'Antique Vase' },
      { id: 't9_3', type: 'emoji', value: '🛋️', label: 'Classic Sofa' },
      { id: 't9_4', type: 'lucide', value: 'Clock', label: 'Antique' },
      { id: 't9_5', type: 'lucide', value: 'Crown', label: 'Royal Heritage' },
      { id: 't9_6', type: 'emoji', value: '🗝️', label: 'Old Key' },
      { id: 't9_7', type: 'lucide', value: 'Landmark', label: 'Heritage' },
      { id: 't9_8', type: 'emoji', value: '📜', label: 'History' },
      { id: 't9_9', type: 'lucide', value: 'Gem', label: 'Rare Item' },
      { id: 't9_10', type: 'emoji', value: '🖼️', label: 'Vintage Frame' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm10',
    name: 'Rushikesh Shukale',
    category: 'Glass Facades',
    company: 'Shukale Glass',
    targetIcons: [
      { id: 't10_1', type: 'emoji', value: '🪟', label: 'Glass Window' },
      { id: 't10_2', type: 'emoji', value: '🏙️', label: 'Glass Skyscraper' },
      { id: 't10_3', type: 'emoji', value: '🏢', label: 'Commercial Complex' },
      { id: 't10_4', type: 'lucide', value: 'Building2', label: 'Facade' },
      { id: 't10_5', type: 'lucide', value: 'Maximize2', label: 'Glass Sheet' },
      { id: 't10_6', type: 'lucide', value: 'Shield', label: 'Safety Glass' },
      { id: 't10_7', type: 'emoji', value: '✨', label: 'Reflective' },
      { id: 't10_8', type: 'lucide', value: 'Sun', label: 'Tinted Facade' },
      { id: 't10_9', type: 'emoji', value: '💎', label: 'Crystal Glass' },
      { id: 't10_10', type: 'lucide', value: 'Maximize', label: 'Wide Facade' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm11',
    name: 'Sachin Palke',
    category: 'Virtual CFO',
    company: 'Palke Advisory',
    targetIcons: [
      { id: 't11_1', type: 'emoji', value: '💼', label: 'Executive CFO' },
      { id: 't11_2', type: 'emoji', value: '📊', label: 'Financial Analytics' },
      { id: 't11_3', type: 'emoji', value: '💻', label: 'Virtual CFO' },
      { id: 't11_4', type: 'lucide', value: 'Calculator', label: 'Financial Planning' },
      { id: 't11_5', type: 'lucide', value: 'TrendingUp', label: 'Corporate Growth' },
      { id: 't11_6', type: 'lucide', value: 'Briefcase', label: 'Corporate' },
      { id: 't11_7', type: 'emoji', value: '💰', label: 'Capital Control' },
      { id: 't11_8', type: 'lucide', value: 'PieChart', label: 'Budget' },
      { id: 't11_9', type: 'emoji', value: '🧠', label: 'Strategy' },
      { id: 't11_10', type: 'lucide', value: 'ShieldCheck', label: 'Compliance' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm12',
    name: 'Nupur Thakur',
    category: 'Soft Furnishings',
    company: 'Thakur Drapes',
    targetIcons: [
      { id: 't12_1', type: 'emoji', value: '🪟', label: 'Curtain' },
      { id: 't12_2', type: 'emoji', value: '🛏️', label: 'Linens' },
      { id: 't12_3', type: 'emoji', value: '🛋️', label: 'Cushions' },
      { id: 't12_4', type: 'lucide', value: 'Shirt', label: 'Fabric' },
      { id: 't12_5', type: 'lucide', value: 'Scissors', label: 'Custom Tailor' },
      { id: 't12_6', type: 'lucide', value: 'Sparkles', label: 'Elegance' },
      { id: 't12_7', type: 'emoji', value: '🎨', label: 'Textile Pattern' },
      { id: 't12_8', type: 'lucide', value: 'Layers', label: 'Drapes' },
      { id: 't12_9', type: 'emoji', value: '🧵', label: 'Thread' },
      { id: 't12_10', type: 'lucide', value: 'Home', label: 'Home Decor' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm13',
    name: 'Yash Jagtap',
    category: 'General Insurance',
    company: 'Jagtap Risk Advisors',
    targetIcons: [
      { id: 't13_1', type: 'emoji', value: '🛡️', label: 'Protection Shield' },
      { id: 't13_2', type: 'emoji', value: '🚗', label: 'Motor Insurance' },
      { id: 't13_3', type: 'emoji', value: '🏢', label: 'Business Insurance' },
      { id: 't13_4', type: 'lucide', value: 'ShieldCheck', label: 'Covered' },
      { id: 't13_5', type: 'lucide', value: 'Car', label: 'Auto Insurance' },
      { id: 't13_6', type: 'lucide', value: 'FileCheck', label: 'Policy' },
      { id: 't13_7', type: 'emoji', value: '✈️', label: 'Travel Policy' },
      { id: 't13_8', type: 'lucide', value: 'Umbrella', label: 'Safety Net' },
      { id: 't13_9', type: 'emoji', value: '🏠', label: 'Property Policy' },
      { id: 't13_10', type: 'lucide', value: 'Lock', label: 'Security' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm14',
    name: 'Chaitanya Gadre',
    category: 'Advocate – Civil Law',
    company: 'Gadre Legal Chambers',
    targetIcons: [
      { id: 't14_1', type: 'emoji', value: '⚖️', label: 'Civil Law' },
      { id: 't14_2', type: 'emoji', value: '📜', label: 'Contract' },
      { id: 't14_3', type: 'emoji', value: '🏛️', label: 'High Court' },
      { id: 't14_4', type: 'lucide', value: 'Scale', label: 'Justice' },
      { id: 't14_5', type: 'lucide', value: 'FileText', label: 'Litigation' },
      { id: 't14_6', type: 'lucide', value: 'Gavel', label: 'Gavel' },
      { id: 't14_7', type: 'emoji', value: '🖊️', label: 'Legal Agreement' },
      { id: 't14_8', type: 'lucide', value: 'Shield', label: 'Advocate' },
      { id: 't14_9', type: 'emoji', value: '💼', label: 'Chambers' },
      { id: 't14_10', type: 'lucide', value: 'BookOpen', label: 'Law Book' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm15',
    name: 'Pandurang Jorvekar',
    category: 'CA – Audits & Tax',
    company: 'Jorvekar & Associates',
    targetIcons: [
      { id: 't15_1', type: 'emoji', value: '🧾', label: 'Tax Audit' },
      { id: 't15_2', type: 'emoji', value: '📊', label: 'Compliance Audit' },
      { id: 't15_3', type: 'emoji', value: '🏛️', label: 'Financial Compliance' },
      { id: 't15_4', type: 'lucide', value: 'Calculator', label: 'Tax Calculation' },
      { id: 't15_5', type: 'lucide', value: 'FileCheck', label: 'Audit Passed' },
      { id: 't15_6', type: 'lucide', value: 'Receipt', label: 'Tax Form' },
      { id: 't15_7', type: 'emoji', value: '💵', label: 'Income Tax' },
      { id: 't15_8', type: 'lucide', value: 'DollarSign', label: 'Revenue' },
      { id: 't15_9', type: 'emoji', value: '🖊️', label: 'CA Sign' },
      { id: 't15_10', type: 'lucide', value: 'PieChart', label: 'Balances' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm16',
    name: 'Pratyoosh Pradhan',
    category: 'Architect – Commercial',
    company: 'Pradhan Commercial Studio',
    targetIcons: [
      { id: 't16_1', type: 'emoji', value: '🏢', label: 'Commercial Complex' },
      { id: 't16_2', type: 'emoji', value: '🏙️', label: 'Office Campus' },
      { id: 't16_3', type: 'emoji', value: '🏗️', label: 'Construction' },
      { id: 't16_4', type: 'lucide', value: 'Building2', label: 'Corporate Tower' },
      { id: 't16_5', type: 'lucide', value: 'Compass', label: 'Masterplan' },
      { id: 't16_6', type: 'lucide', value: 'Landmark', label: 'Commercial Plaza' },
      { id: 't16_7', type: 'emoji', value: '📐', label: 'Commercial Layout' },
      { id: 't16_8', type: 'lucide', value: 'Ruler', label: 'Elevation' },
      { id: 't16_9', type: 'emoji', value: '🏬', label: 'Mall Architecture' },
      { id: 't16_10', type: 'lucide', value: 'Layers', label: 'Floors' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm17',
    name: 'Hrithik Kumbhar',
    category: 'Digital Marketing & Ads',
    company: 'Kumbhar Media',
    targetIcons: [
      { id: 't17_1', type: 'emoji', value: '📱', label: 'Social Media' },
      { id: 't17_2', type: 'emoji', value: '🎯', label: 'Targeted Ads' },
      { id: 't17_3', type: 'emoji', value: '🚀', label: 'Viral Growth' },
      { id: 't17_4', type: 'lucide', value: 'Target', label: 'Lead Gen' },
      { id: 't17_5', type: 'lucide', value: 'Megaphone', label: 'Digital Ads' },
      { id: 't17_6', type: 'lucide', value: 'TrendingUp', label: 'SEO Traffic' },
      { id: 't17_7', type: 'emoji', value: '💻', label: 'Online Funnel' },
      { id: 't17_8', type: 'lucide', value: 'Globe', label: 'Web Campaign' },
      { id: 't17_9', type: 'emoji', value: '🔥', label: 'Hot Leads' },
      { id: 't17_10', type: 'lucide', value: 'BarChart', label: 'ROAS Analytics' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm18',
    name: 'Archana Devkate',
    category: 'Life Insurance Advisor',
    company: 'Devkate Financial Care',
    targetIcons: [
      { id: 't18_1', type: 'emoji', value: '👨‍👩‍👧‍👦', label: 'Family Protection' },
      { id: 't18_2', type: 'emoji', value: '❤️', label: 'Life Care' },
      { id: 't18_3', type: 'emoji', value: '🛡️', label: 'Term Plan' },
      { id: 't18_4', type: 'lucide', value: 'Heart', label: 'Family Life' },
      { id: 't18_5', type: 'lucide', value: 'ShieldCheck', label: 'Secure Future' },
      { id: 't18_6', type: 'lucide', value: 'PiggyBank', label: 'Child Education' },
      { id: 't18_7', type: 'emoji', value: '🌴', label: 'Retirement Plan' },
      { id: 't18_8', type: 'lucide', value: 'FileText', label: 'Policy Document' },
      { id: 't18_9', type: 'emoji', value: '💵', label: 'Guaranteed Return' },
      { id: 't18_10', type: 'lucide', value: 'Umbrella', label: 'Family Umbrella' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm19',
    name: 'Srinath Gilda',
    category: 'Home Loans & Mortgage',
    company: 'Gilda Capital',
    targetIcons: [
      { id: 't19_1', type: 'emoji', value: '🏡', label: 'Dream Home' },
      { id: 't19_2', type: 'emoji', value: '🔑', label: 'Home Key' },
      { id: 't19_3', type: 'emoji', value: '🏦', label: 'Housing Bank' },
      { id: 't19_4', type: 'lucide', value: 'Home', label: 'Property Purchase' },
      { id: 't19_5', type: 'lucide', value: 'KeyRound', label: 'Loan Approval' },
      { id: 't19_6', type: 'lucide', value: 'Percent', label: 'Lowest Interest' },
      { id: 't19_7', type: 'emoji', value: '📄', label: 'Sanction Letter' },
      { id: 't19_8', type: 'lucide', value: 'DollarSign', label: 'Mortgage Capital' },
      { id: 't19_9', type: 'emoji', value: '🧱', label: 'Construction Loan' },
      { id: 't19_10', type: 'lucide', value: 'CheckCircle', label: 'Fast Disbursal' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm20',
    name: 'Amol Kale',
    category: 'Fire Safety & Alarms',
    company: 'Kale Fire Systems',
    targetIcons: [
      { id: 't20_1', type: 'emoji', value: '🔥', label: 'Fire Extinguisher' },
      { id: 't20_2', type: 'emoji', value: '🚨', label: 'Fire Alarm' },
      { id: 't20_3', type: 'emoji', value: '🧯', label: 'Extinguisher Bottle' },
      { id: 't20_4', type: 'lucide', value: 'Flame', label: 'Fire Protection' },
      { id: 't20_5', type: 'lucide', value: 'ShieldAlert', label: 'Hazard Safety' },
      { id: 't20_6', type: 'lucide', value: 'Bell', label: 'Fire Bell' },
      { id: 't20_7', type: 'emoji', value: '💧', label: 'Sprinkler System' },
      { id: 't20_8', type: 'lucide', value: 'Shield', label: 'NOC Certification' },
      { id: 't20_9', type: 'emoji', value: '⚡', label: 'Emergency Sensor' },
      { id: 't20_10', type: 'lucide', value: 'CheckSquare', label: 'Audit NOC' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm21',
    name: 'Dr. Seema Rathod',
    category: 'Dentist & Smile Care',
    company: 'Smile Dental Clinic',
    targetIcons: [
      { id: 't21_1', type: 'emoji', value: '🦷', label: 'Tooth' },
      { id: 't21_2', type: 'emoji', value: '🩺', label: 'Stethoscope' },
      { id: 't21_3', type: 'emoji', value: '🪥', label: 'Toothbrush' },
      { id: 't21_4', type: 'emoji', value: '😁', label: 'Grin' },
      { id: 't21_5', type: 'lucide', value: 'Stethoscope', label: 'Doctor' },
      { id: 't21_6', type: 'lucide', value: 'HeartPulse', label: 'Health' },
      { id: 't21_7', type: 'emoji', value: '💊', label: 'Dental Care' },
      { id: 't21_8', type: 'lucide', value: 'Activity', label: 'Clinic' },
      { id: 't21_9', type: 'emoji', value: '🏥', label: 'Hospital' },
      { id: 't21_10', type: 'lucide', value: 'Smile', label: 'Perfect Smile' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm22',
    name: 'Vijay Rasote',
    category: 'Commercial Loans',
    company: 'Rasote Financial Solutions',
    targetIcons: [
      { id: 't22_1', type: 'emoji', value: '🏭', label: 'Factory Expansion' },
      { id: 't22_2', type: 'emoji', value: '💰', label: 'Capital Finance' },
      { id: 't22_3', type: 'emoji', value: '🏢', label: 'Business Working Capital' },
      { id: 't22_4', type: 'lucide', value: 'Building', label: 'Corporate Funding' },
      { id: 't22_5', type: 'lucide', value: 'DollarSign', label: 'Business Loan' },
      { id: 't22_6', type: 'lucide', value: 'Briefcase', label: 'Commercial Credit' },
      { id: 't22_7', type: 'emoji', value: '📈', label: 'Scaling Capital' },
      { id: 't22_8', type: 'lucide', value: 'TrendingUp', label: 'SME Loan' },
      { id: 't22_9', type: 'emoji', value: '📑', label: 'Loan Approval' },
      { id: 't22_10', type: 'lucide', value: 'CheckCircle2', label: 'Funded' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm23',
    name: 'Rajesh Kumawat',
    category: 'App Developer – Mobile',
    company: 'Kumawat Tech',
    targetIcons: [
      { id: 't23_1', type: 'emoji', value: '📲', label: 'Mobile App' },
      { id: 't23_2', type: 'emoji', value: '💻', label: 'Coding' },
      { id: 't23_3', type: 'emoji', value: '🤖', label: 'Android App' },
      { id: 't23_4', type: 'lucide', value: 'Smartphone', label: 'iOS & Android' },
      { id: 't23_5', type: 'lucide', value: 'Code', label: 'Code' },
      { id: 't23_6', type: 'lucide', value: 'Cpu', label: 'Software Engine' },
      { id: 't23_7', type: 'emoji', value: '⚡', label: 'Fast App' },
      { id: 't23_8', type: 'lucide', value: 'Globe', label: 'API Backend' },
      { id: 't23_9', type: 'emoji', value: '🍏', label: 'Apple iOS' },
      { id: 't23_10', type: 'lucide', value: 'Layers', label: 'UI/UX Mobile' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm24',
    name: 'Vijendra Wayal',
    category: 'Interior Turnkey Contracting',
    company: 'Wayal Turnkey Projects',
    targetIcons: [
      { id: 't24_1', type: 'emoji', value: '🔨', label: 'Turnkey Execution' },
      { id: 't24_2', type: 'emoji', value: '🏗️', label: 'Interior Fitouts' },
      { id: 't24_3', type: 'emoji', value: '🛠️', label: 'Contractor Tools' },
      { id: 't24_4', type: 'lucide', value: 'Wrench', label: 'Site Execution' },
      { id: 't24_5', type: 'lucide', value: 'HardHat', label: 'Site Safety' },
      { id: 't24_6', type: 'lucide', value: 'CheckSquare', label: 'Project Completed' },
      { id: 't24_7', type: 'emoji', value: '🏠', label: 'Turnkey Flat' },
      { id: 't24_8', type: 'lucide', value: 'Home', label: 'Interior Project' },
      { id: 't24_9', type: 'emoji', value: '📦', label: 'Material Supply' },
      { id: 't24_10', type: 'lucide', value: 'Sparkles', label: 'Flawless Finish' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm25',
    name: 'Dr. Vitthal Bhosale',
    category: 'Horticulture & Landscape',
    company: 'Bhosale Landscaping',
    targetIcons: [
      { id: 't25_1', type: 'emoji', value: '🌱', label: 'Plantation' },
      { id: 't25_2', type: 'emoji', value: '🌳', label: 'Trees' },
      { id: 't25_3', type: 'emoji', value: '🪴', label: 'Landscaping' },
      { id: 't25_4', type: 'lucide', value: 'Flower2', label: 'Garden' },
      { id: 't25_5', type: 'lucide', value: 'Trees', label: 'Landscape Plan' },
      { id: 't25_6', type: 'lucide', value: 'Sun', label: 'Horticulture' },
      { id: 't25_7', type: 'emoji', value: '🌾', label: 'Organic Soil' },
      { id: 't25_8', type: 'lucide', value: 'Sparkles', label: 'Green Lawn' },
      { id: 't25_9', type: 'emoji', value: '🌺', label: 'Flowers' },
      { id: 't25_10', type: 'lucide', value: 'Compass', label: 'Botanical Layout' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm26',
    name: 'Hinendra Surana',
    category: 'Custom Product Packaging',
    company: 'Surana Packaging',
    targetIcons: [
      { id: 't26_1', type: 'emoji', value: '📦', label: 'Custom Box' },
      { id: 't26_2', type: 'emoji', value: '🛍️', label: 'Branded Bag' },
      { id: 't26_3', type: 'emoji', value: '🏷️', label: 'Product Tag' },
      { id: 't26_4', type: 'lucide', value: 'Box', label: 'Corrugated Box' },
      { id: 't26_5', type: 'lucide', value: 'Package', label: 'Shipment Package' },
      { id: 't26_6', type: 'lucide', value: 'Tag', label: 'Branded Label' },
      { id: 't26_7', type: 'emoji', value: '🎁', label: 'Gift Box' },
      { id: 't26_8', type: 'lucide', value: 'Shield', label: 'Durable Packing' },
      { id: 't26_9', type: 'emoji', value: '✉️', label: 'Custom Mailer' },
      { id: 't26_10', type: 'lucide', value: 'Layers', label: 'Packaging Foils' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm27',
    name: 'Siddharth Sonawane',
    category: 'Leisure Travel & Holidays',
    company: 'Sonawane Travel Club',
    targetIcons: [
      { id: 't27_1', type: 'emoji', value: '✈️', label: 'Flight' },
      { id: 't27_2', type: 'emoji', value: '🏖️', label: 'Beach Vacation' },
      { id: 't27_3', type: 'emoji', value: '🧳', label: 'Luggage' },
      { id: 't27_4', type: 'lucide', value: 'Plane', label: 'Holiday Tour' },
      { id: 't27_5', type: 'lucide', value: 'Palmtree', label: 'Resort' },
      { id: 't27_6', type: 'lucide', value: 'Compass', label: 'Travel Guide' },
      { id: 't27_7', type: 'emoji', value: '🗽', label: 'Sightseeing' },
      { id: 't27_8', type: 'lucide', value: 'MapPin', label: 'Destination' },
      { id: 't27_9', type: 'emoji', value: '🎫', label: 'Tour Tickets' },
      { id: 't27_10', type: 'lucide', value: 'Sun', label: 'Sunny Getaway' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm28',
    name: 'Kajal Agarwal',
    category: 'Bespoke Fashion Designer',
    company: 'Kajal Couture',
    targetIcons: [
      { id: 't28_1', type: 'emoji', value: '👗', label: 'Designer Gown' },
      { id: 't28_2', type: 'emoji', value: '🥻', label: 'Bridal Saree' },
      { id: 't28_3', type: 'emoji', value: '👑', label: 'Couture' },
      { id: 't28_4', type: 'lucide', value: 'Shirt', label: 'Bespoke Outfit' },
      { id: 't28_5', type: 'lucide', value: 'Scissors', label: 'Tailoring' },
      { id: 't28_6', type: 'lucide', value: 'Sparkles', label: 'Glamour' },
      { id: 't28_7', type: 'emoji', value: '🧵', label: 'Embroidery' },
      { id: 't28_8', type: 'lucide', value: 'Crown', label: 'High Fashion' },
      { id: 't28_9', type: 'emoji', value: '👠', label: 'Fashion Show' },
      { id: 't28_10', type: 'lucide', value: 'Gem', label: 'Luxury Wear' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm29',
    name: 'Rohit Chavan',
    category: 'Modular Kitchen Studio',
    company: 'Chavan Kitchens',
    targetIcons: [
      { id: 't29_1', type: 'emoji', value: '🍳', label: 'Modular Kitchen' },
      { id: 't29_2', type: 'emoji', value: '🥘', label: 'Ergonomic Cooking' },
      { id: 't29_3', type: 'emoji', value: '🍽️', label: 'Kitchenware' },
      { id: 't29_4', type: 'lucide', value: 'Utensils', label: 'Modern Kitchen' },
      { id: 't29_5', type: 'lucide', value: 'Box', label: 'Modular Cabinets' },
      { id: 't29_6', type: 'lucide', value: 'Flame', label: 'Stove Top' },
      { id: 't29_7', type: 'emoji', value: '🗄️', label: 'Pullout Drawers' },
      { id: 't29_8', type: 'lucide', value: 'Sparkles', label: 'Granite Counter' },
      { id: 't29_9', type: 'emoji', value: '🔪', label: 'Chef Kitchen' },
      { id: 't29_10', type: 'lucide', value: 'Maximize2', label: 'Compact Layout' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm30',
    name: 'Ameya Tarde',
    category: 'Wildlife Safaris & Tours',
    company: 'Tarde Expeditions',
    targetIcons: [
      { id: 't30_1', type: 'emoji', value: '🐅', label: 'Tiger Safari' },
      { id: 't30_2', type: 'emoji', value: '🐘', label: 'Elephant Tour' },
      { id: 't30_3', type: 'emoji', value: '🏕️', label: 'Jungle Camp' },
      { id: 't30_4', type: 'lucide', value: 'Compass', label: 'Guided Safari' },
      { id: 't30_5', type: 'lucide', value: 'Camera', label: 'Wildlife Photo' },
      { id: 't30_6', type: 'lucide', value: 'Trees', label: 'National Park' },
      { id: 't30_7', type: 'emoji', value: '🦜', label: 'Exotic Birds' },
      { id: 't30_8', type: 'lucide', value: 'Binoculars', label: 'Spotting' },
      { id: 't30_9', type: 'emoji', value: '⛰️', label: 'Wilderness' },
      { id: 't30_10', type: 'lucide', value: 'Sun', label: 'Adventure' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm31',
    name: 'Abhishek Dhandekar',
    category: 'Sanitary Fittings & Bath',
    company: 'Dhandekar Bath Studio',
    targetIcons: [
      { id: 't31_1', type: 'emoji', value: '🚿', label: 'Shower' },
      { id: 't31_2', type: 'emoji', value: '🛁', label: 'Bathtub' },
      { id: 't31_3', type: 'emoji', value: '🚰', label: 'Faucet' },
      { id: 't31_4', type: 'lucide', value: 'Droplet', label: 'Water Fitting' },
      { id: 't31_5', type: 'lucide', value: 'Sparkles', label: 'Chrome Finish' },
      { id: 't31_6', type: 'lucide', value: 'Home', label: 'Bathroom Decor' },
      { id: 't31_7', type: 'emoji', value: '🧼', label: 'Sanitary Care' },
      { id: 't31_8', type: 'lucide', value: 'Shield', label: 'Leakproof Fitting' },
      { id: 't31_9', type: 'emoji', value: '💧', label: 'Pure Flow' },
      { id: 't31_10', type: 'lucide', value: 'Maximize', label: 'Luxury Fitting' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm32',
    name: 'Ketan Bhosale',
    category: 'Interior Designer – Commercial',
    company: 'Bhosale Commercial Interiors',
    targetIcons: [
      { id: 't32_1', type: 'emoji', value: '🏬', label: 'Store Interior' },
      { id: 't32_2', type: 'emoji', value: '🏢', label: 'Office Fitout' },
      { id: 't32_3', type: 'emoji', value: '🛋️', label: 'Reception Lounge' },
      { id: 't32_4', type: 'lucide', value: 'Building2', label: 'Showroom Design' },
      { id: 't32_5', type: 'lucide', value: 'Layout', label: 'Floor Plan' },
      { id: 't32_6', type: 'lucide', value: 'Lightbulb', label: 'Commercial Lighting' },
      { id: 't32_7', type: 'emoji', value: '💼', label: 'Corporate Interior' },
      { id: 't32_8', type: 'lucide', value: 'Sparkles', label: 'Modern Finish' },
      { id: 't32_9', type: 'emoji', value: '🖥️', label: 'Workstations' },
      { id: 't32_10', type: 'lucide', value: 'Layers', label: 'Acoustic Panels' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm33',
    name: 'Nikita Gurav',
    category: 'Tarot Card Reader & Guidance',
    company: 'Gurav Intuitive Clarity',
    targetIcons: [
      { id: 't33_1', type: 'emoji', value: '🔮', label: 'Crystal Ball' },
      { id: 't33_2', type: 'emoji', value: '🃏', label: 'Tarot Cards' },
      { id: 't33_3', type: 'emoji', value: '✨', label: 'Intuition' },
      { id: 't33_4', type: 'lucide', value: 'Sparkles', label: 'Cosmic Energy' },
      { id: 't33_5', type: 'lucide', value: 'Moon', label: 'Guidance' },
      { id: 't33_6', type: 'lucide', value: 'Sun', label: 'Clarity' },
      { id: 't33_7', type: 'emoji', value: '🌙', label: 'Moon Energy' },
      { id: 't33_8', type: 'lucide', value: 'Eye', label: 'Insight' },
      { id: 't33_9', type: 'emoji', value: '⭐', label: 'Destiny' },
      { id: 't33_10', type: 'lucide', value: 'Wand2', label: 'Tarot Reading' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
  {
    id: 'm34',
    name: 'Rati Oke',
    category: 'Wealth Management',
    company: 'Oke Wealth Partners',
    targetIcons: [
      { id: 't34_1', type: 'emoji', value: '💎', label: 'High Net Worth' },
      { id: 't34_2', type: 'emoji', value: '📊', label: 'Wealth Portfolio' },
      { id: 't34_3', type: 'emoji', value: '💰', label: 'Asset Management' },
      { id: 't34_4', type: 'lucide', value: 'TrendingUp', label: 'Capital Growth' },
      { id: 't34_5', type: 'lucide', value: 'ShieldCheck', label: 'Risk Mitigation' },
      { id: 't34_6', type: 'lucide', value: 'PieChart', label: 'Asset Allocation' },
      { id: 't34_7', type: 'emoji', value: '🏛️', label: 'Family Office' },
      { id: 't34_8', type: 'lucide', value: 'Briefcase', label: 'Private Wealth' },
      { id: 't34_9', type: 'emoji', value: '📜', label: 'Estate Plan' },
      { id: 't34_10', type: 'lucide', value: 'DollarSign', label: 'Financial Freedom' },
    ],
    distractorIcons: DEFAULT_DISTRACTOR_POOL,
  },
];

export const INITIAL_MEMBERS: MemberProfile[] = RAW_INITIAL_MEMBERS.map((m, idx) => ({
  ...m,
  distractorIcons:
    m.id === 'm1' && m.distractorIcons && m.distractorIcons.length >= 30
      ? m.distractorIcons
      : getMemberUniqueDistractors(idx, m.targetIcons),
}));
